import { mkdir, writeFile } from "node:fs/promises";
import { readdirSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { PNG } from "pngjs";
import { encodePng, hex } from "./write-png.mjs";

/** Contact sheets (#166): every `src/assets/icons/*.png` composited alphabetically on the real
 * panel color at true in-game scale, at 4x for pixel diagnosis, and as a flat-color 1x silhouette
 * for recognition-before-shading review. Committed under `docs/icon-*-sheet*.png`, regenerated by
 * `npm run art`, and checked for staleness by icon-assets.test.ts. */
const CELL = 34;
const GUTTER = 4;
const PANEL_BG = "#262019";
const SILHOUETTE = "#c6ad79";
const SCALE_4X = 4;

function loadIconsAlphabetically(iconsDir) {
  const files = readdirSync(iconsDir)
    .filter((f) => f.endsWith(".png"))
    .sort();
  return files.map((f) => ({
    name: f.replace(/\.png$/, ""),
    png: PNG.sync.read(readFileSync(resolve(iconsDir, f))),
  }));
}

/** A roughly-square grid: enough columns that `columns * columns >= count`, matching how many
 * rows are needed so the sheet isn't a single very-wide strip. */
function layoutGrid(count) {
  const columns = Math.max(1, Math.ceil(Math.sqrt(count)));
  const rows = Math.max(1, Math.ceil(count / columns));
  return { columns, rows };
}

/** Builds the 1x sheet's `pixel(x, y)` function: a `columns`x`rows` grid of 34px icon cells with
 * 4px gutters, alpha-blended onto `PANEL_BG` so a partially-translucent icon (e.g. shade-wisp)
 * reads against the real panel color instead of a hard cutout. */
function sheetPixelFn(icons, columns, rows, silhouetteOnly = false) {
  const [bgR, bgG, bgB] = hex(PANEL_BG);
  const [silhouetteR, silhouetteG, silhouetteB] = hex(SILHOUETTE);
  const stride = CELL + GUTTER;
  return (x, y) => {
    const col = Math.floor(x / stride);
    const row = Math.floor(y / stride);
    const localX = x - col * stride;
    const localY = y - row * stride;
    const idx = row * columns + col;
    if (localX >= CELL || localY >= CELL || col >= columns || row >= rows || idx >= icons.length) {
      return [bgR, bgG, bgB, 255];
    }
    const icon = icons[idx].png;
    const at = (icon.width * localY + localX) << 2;
    const a = icon.data[at + 3];
    if (a === 0) return [bgR, bgG, bgB, 255];
    const t = a / 255;
    const sourceR = silhouetteOnly ? silhouetteR : icon.data[at];
    const sourceG = silhouetteOnly ? silhouetteG : icon.data[at + 1];
    const sourceB = silhouetteOnly ? silhouetteB : icon.data[at + 2];
    return [
      Math.round(sourceR * t + bgR * (1 - t)),
      Math.round(sourceG * t + bgG * (1 - t)),
      Math.round(sourceB * t + bgB * (1 - t)),
      255,
    ];
  };
}

/** Pure builder — no filesystem writes — so `icon-assets.test.ts`'s sync-check compares the exact
 * bytes a regeneration would produce, and `writeContactSheets` below is just this plus disk I/O. */
export function buildContactSheets(iconsDir) {
  const icons = loadIconsAlphabetically(iconsDir);
  const { columns, rows } = layoutGrid(icons.length);
  const width = columns * CELL + (columns - 1) * GUTTER;
  const height = rows * CELL + (rows - 1) * GUTTER;
  const pixel1x = sheetPixelFn(icons, columns, rows);
  const silhouettePixel1x = sheetPixelFn(icons, columns, rows, true);
  const onePx = encodePng(width, height, pixel1x);
  const fourX = encodePng(width * SCALE_4X, height * SCALE_4X, (x, y) =>
    pixel1x(Math.floor(x / SCALE_4X), Math.floor(y / SCALE_4X)),
  );
  const silhouetteOnePx = encodePng(width, height, silhouettePixel1x);
  return { onePx, fourX, silhouetteOnePx };
}

/** Regenerates the committed color and silhouette sheets. Called from `generate.mjs` (`npm run
 * art`). */
export async function writeContactSheets(iconsDir, docsDir) {
  const { onePx, fourX, silhouetteOnePx } = buildContactSheets(iconsDir);
  await mkdir(docsDir, { recursive: true });
  await writeFile(resolve(docsDir, "icon-sheet-1x.png"), onePx);
  await writeFile(resolve(docsDir, "icon-sheet-4x.png"), fourX);
  await writeFile(resolve(docsDir, "icon-silhouette-sheet-1x.png"), silhouetteOnePx);
}
