import type { Content } from "../core/types";
import { composeContent } from "./area-content";
import { lumbryMeadows } from "./areas/lumbry-meadows";
import { darkrootForest } from "./areas/darkroot-forest";
import { oldSewers } from "./areas/old-sewers";
import { boneCrypt } from "./areas/bone-crypt";
import { frostspire } from "./areas/frostspire";
import { ladderArmour, ladderRecipe, ladderWeapon } from "./tier-ladder";

/**
 * v1 content: shared Items/Recipes/Spells/Vendor/Pets plus composed Area bundles.
 * Data only — conforms to core types, never imports engine code (ADR-0001).
 */
// Combat Depth wave 4/4 (#102) monster re-stat: every Monster below gets a real per-Attack-Type
// `def` vector so it has a genuine weak spot (its lowest `def` entry, >=~40% below its strongest
// at that Monster's tier) instead of wave 1-3's uniform-zero placeholder. Rules of thumb encoded
// per-Monster below: soft beasts (chicken/cow/giant-rat/wolf) are weak to slash; light-armoured
// humanoids (goblin family/bandit) are weak to stab; bony undead (skeleton) are weak to crush;
// ethereal/caster Monsters (hollow-warden/crypt-shade) defend melee well and lean on a non-melee
// or off-melee weak spot; every Monster keeps decent-but-beatable def in its non-weak types so the
// matrix rewards switching without punishing ignoring it into unwinnability. Only bosses plus the
// Zombie carry a `weakElement`, keeping Magic's ×1.5 multiplier a boss tool. Exact numbers are
// tuning defaults, flagged as such — a later balance pass may retune them.
export const content: Content = composeContent(
  [lumbryMeadows, darkrootForest, oldSewers, boneCrypt, frostspire],
  {
    items: [
      { kind: "currency", id: "gold", name: "Gold", icon: "gold" },
      {
        kind: "food",
        id: "cooked-meat",
        name: "Cooked Meat",
        icon: "cooked-meat",
        heals: 4,
        value: 3,
      },
      // Gear Tier ladder (#251): generated by src/data/tier-ladder.ts's per-item accessors, called
      // in place — every id below keeps its exact pre-#251 array index (saves persist raw item ids).
      ladderWeapon("bronze", "dagger"),
      ladderWeapon("bronze", "sword"),
      // Gap-fill crush weapon (Combat Depth #102): no mace exists at any tier before this — atk/str
      // land between the tier's dagger and sword, same attackSpeed as the sword/dagger family.
      ladderWeapon("bronze", "mace"),
      {
        kind: "equipment",
        id: "leather-body",
        name: "Leather Body",
        icon: "leather-body",
        slot: "body",
        // Re-stat (#116, Crafting's ranged-armour line): leather is now the LIGHT-armour shape —
        // low stab/slash/crush, higher ranged/magic def — rather than #102's "modest melee, anti-
        // caster" numbers. Still beats every metal body's magic def (armour-directional.test.ts),
        // and is now craftable (see craft-leather-body below) in addition to its existing rare drop.
        def: { stab: 2, slash: 2, crush: 3, ranged: 6, magic: 5 },
        value: 20,
      },
      // Legacy id override (#251): the kiteshield family's bronze tier shipped as "bronze-shield" /
      // "Bronze Shield" rather than the generated "bronze-kiteshield" — never renamed, saves persist
      // this id. tier-ladder.ts's ladderArmour applies the override; def/value reproduce exactly.
      ladderArmour("bronze", "kiteshield"),
      {
        kind: "equipment",
        id: "goblin-charm",
        name: "Goblin Charm",
        icon: "goblin-charm",
        slot: "head",
        // Armour re-stat (#102, tuning defaults): keeps its flavor, given a small magic lean.
        def: { stab: 1, slash: 1, crush: 1, ranged: 1, magic: 3 },
        value: 150,
      },
      {
        kind: "food",
        id: "cooked-trout",
        name: "Cooked Trout",
        icon: "cooked-trout",
        heals: 8,
        value: 8,
      },
      // Gear Tier ladder (#251): see the comment above bronze-dagger — accessors called in place.
      ladderWeapon("iron", "dagger"),
      ladderArmour("iron", "chainbody"),
      ladderArmour("iron", "kiteshield"),
      ladderArmour("iron", "full-helm"),
      // Gap-fill iron-tier slash/crush weapons (Combat Depth #102): only bronze-sword existed
      // before this at any tier; mace atk/str land between the tier's dagger and sword.
      ladderWeapon("iron", "sword"),
      ladderWeapon("iron", "mace"),
      // Append-only: ids are referenced by saves (Food Slots persist an itemId, #61), so never
      // reorder above. Content order no longer drives autoEat — that's Food Slot order now.
      {
        kind: "food",
        id: "cooked-shrimp",
        name: "Cooked Shrimp",
        icon: "cooked-shrimp",
        heals: 3,
        value: 2,
      },
      // Smithing materials (#28): dropped by Monsters above, consumed by recipes below.
      { kind: "material", id: "bronze-bar", name: "Bronze Bar", icon: "bronze-bar", value: 8 },
      { kind: "material", id: "iron-bar", name: "Iron Bar", icon: "iron-bar", value: 20 },
      // Old Sewers (#10): steel Equipment tier and a stronger Food. Append-only — see the
      // append-only comment above cooked-shrimp; these go after iron-bar, never earlier.
      // Gear Tier ladder (#251): see the comment above bronze-dagger — accessors called in place.
      // Steel Smithing recipes now exist for every family below (see the recipes array) — steel is
      // no longer drop-only, part of this slice's deliberate rebalance.
      ladderWeapon("steel", "dagger"),
      ladderArmour("steel", "chainbody"),
      ladderArmour("steel", "kiteshield"),
      ladderArmour("steel", "full-helm"),
      ladderWeapon("steel", "sword"),
      ladderWeapon("steel", "mace"),
      {
        kind: "food",
        id: "cooked-pike",
        name: "Cooked Pike",
        icon: "cooked-pike",
        heals: 12,
        value: 15,
      },
      // Bone Crypt (#11): the mithril Equipment tier and the Shade Blade, the best weapon in the
      // game. Append-only — see the append-only comment above cooked-shrimp; these go after
      // cooked-pike, never earlier.
      // Gear Tier ladder (#251): see the comment above bronze-dagger — accessors called in place.
      // Mithril Smithing recipes now exist for every family below (see the recipes array) — mithril
      // is no longer drop-only, part of this slice's deliberate rebalance.
      ladderWeapon("mithril", "dagger"),
      ladderArmour("mithril", "chainbody"),
      ladderArmour("mithril", "kiteshield"),
      ladderArmour("mithril", "full-helm"),
      ladderWeapon("mithril", "sword"),
      ladderWeapon("mithril", "mace"),
      {
        kind: "equipment",
        id: "shade-blade",
        name: "Shade Blade",
        icon: "shade-blade",
        slot: "weapon",
        attackType: "slash",
        atkBonus: 40,
        strBonus: 34,
        def: { stab: 0, slash: 0, crush: 0, ranged: 0, magic: 0 },
        attackSpeed: 3,
        value: 1000,
      },
      // Ranged and Magic starter weapons (#7): the first two Equipment in Content whose attackType
      // (#99) is ranged/magic rather than a melee sub-type — every weapon above this line is melee
      // (stab/slash). Dropped by Lumbry Meadows Monsters (see goblin/cow dropTable above) so the two
      // new Skills are demoable from the very first Area. Append-only — after shade-blade, never
      // earlier.
      // Gear Tier ladder (#251): see the comment above bronze-dagger — accessors called in place.
      // Legacy id override: bronze staff/shortbow shipped as "shortbow"/"apprentice-staff" rather
      // than the generated "bronze-shortbow"/"bronze-staff" — never renamed, saves persist these.
      ladderWeapon("bronze", "shortbow"),
      ladderWeapon("bronze", "staff"),
      // Ranged/Magic tier progression (#13): iron/steel/mithril bows and staves. Since #251, their
      // atk/str no longer reproduce the pre-#251 shipped numbers exactly (only bronze/melee do) —
      // part of the deliberate rebalance; see tier-ladder.test.ts for the worked replacement table.
      // Append-only — after apprentice-staff, never earlier.
      ladderWeapon("iron", "shortbow"),
      ladderWeapon("iron", "staff"),
      ladderWeapon("steel", "shortbow"),
      ladderWeapon("steel", "staff"),
      ladderWeapon("mithril", "shortbow"),
      ladderWeapon("mithril", "staff"),
      // Cooking wave (#115): raw fish/beast Materials — fishing spots and monster drop tables that
      // used to yield cooked Food (see the "#115: cooked-X -> raw-X" comments above) now yield
      // these instead; Cooking recipes (below) convert them back to the same cooked Food. Append-
      // only — after mithril-staff, never earlier.
      { kind: "material", id: "raw-beef", name: "Raw Beef", icon: "raw-beef", value: 1 },
      { kind: "material", id: "raw-shrimp", name: "Raw Shrimp", icon: "raw-shrimp", value: 1 },
      { kind: "material", id: "raw-trout", name: "Raw Trout", icon: "raw-trout", value: 2 },
      { kind: "material", id: "raw-pike", name: "Raw Pike", icon: "raw-pike", value: 3 },
      // Crafting wave (#116): hide Materials, dropped by the four beasts (see the "#116: hide drop"
      // comments on chicken/cow/wolf/giant-rat's dropTables above) and consumed by the Crafting
      // recipes below. Append-only — after raw-pike, never earlier.
      { kind: "material", id: "cowhide", name: "Cowhide", icon: "cowhide", value: 2 },
      { kind: "material", id: "wolf-hide", name: "Wolf Hide", icon: "wolf-hide", value: 4 },
      { kind: "material", id: "thick-hide", name: "Thick Hide", icon: "thick-hide", value: 8 },
      // Crafting wave (#116): the base leather tier's other two pieces (leather-body itself already
      // exists above, re-stat'd to this same light-armour shape — see its own comment). Light armour
      // (#99's Combat Depth Defence Vector split): low stab/slash/crush, higher ranged/magic def, no
      // atk/str (armour never carries those — see validateContent's weapon-only invariant).
      {
        kind: "equipment",
        id: "leather-chaps",
        name: "Leather Chaps",
        icon: "leather-chaps",
        slot: "legs",
        def: { stab: 1, slash: 1, crush: 2, ranged: 4, magic: 3 },
        value: 15,
      },
      {
        kind: "equipment",
        id: "leather-coif",
        name: "Leather Coif",
        icon: "leather-coif",
        slot: "head",
        def: { stab: 1, slash: 1, crush: 1, ranged: 3, magic: 2 },
        value: 12,
      },
      // Crafting wave (#116): the hard-leather tier — wolf-hide/thick-hide inputs, levelReq 20+ (see
      // the Crafting recipes below). Same light-armour shape as the base tier, scaled up: bigger
      // ranged/magic def, melee def stays low relative to it.
      {
        kind: "equipment",
        id: "hard-leather-coif",
        name: "Hard Leather Coif",
        icon: "hard-leather-coif",
        slot: "head",
        def: { stab: 1, slash: 1, crush: 2, ranged: 5, magic: 4 },
        value: 35,
      },
      {
        kind: "equipment",
        id: "hard-leather-chaps",
        name: "Hard Leather Chaps",
        icon: "hard-leather-chaps",
        slot: "legs",
        def: { stab: 2, slash: 2, crush: 3, ranged: 7, magic: 5 },
        value: 45,
      },
      {
        kind: "equipment",
        id: "hard-leather-body",
        name: "Hard Leather Body",
        icon: "hard-leather-body",
        slot: "body",
        def: { stab: 3, slash: 3, crush: 4, ranged: 10, magic: 8 },
        value: 60,
      },
      // Crafting wave (#117): Crafting's jewelry line — gem Materials, dropped by Monsters in the
      // three tiered Areas (see the "#117: gem drop" comments on wolf/goblin-warrior/bandit,
      // giant-rat/zombie/skeleton, and crypt-shade's dropTables above) and consumed by the jewelry
      // Crafting recipes below. Append-only — after hard-leather-body, never earlier.
      { kind: "material", id: "sapphire", name: "Sapphire", icon: "sapphire", value: 15 },
      { kind: "material", id: "emerald", name: "Emerald", icon: "emerald", value: 30 },
      { kind: "material", id: "ruby", name: "Ruby", icon: "ruby", value: 60 },
      // Jewelry (#117): the amulet/ring Gear Slots (types.ts) are an OFFENCE slot (owner decision,
      // grilled, verbatim: "amulets/rings may carry atk/str bonuses, unlike armour") — mechanically
      // distinct from every other armour slot above, which never carries atk/str. Each gem tier's
      // atk/str stays well under the matching-tier weapon's own (e.g. ruby-amulet's 10/7 vs
      // mithril-dagger's 19/15) so jewelry augments a build rather than replacing its weapon choice,
      // plus a small magic-leaning def vector (a gem pendant/band, not armour plating).
      {
        kind: "equipment",
        id: "sapphire-amulet",
        name: "Sapphire Amulet",
        icon: "sapphire-amulet",
        slot: "amulet",
        atkBonus: 3,
        strBonus: 2,
        rangedStr: 2,
        def: { stab: 0, slash: 0, crush: 0, ranged: 0, magic: 1 },
        value: 60,
      },
      {
        kind: "equipment",
        id: "sapphire-ring",
        name: "Sapphire Ring",
        icon: "sapphire-ring",
        slot: "ring",
        atkBonus: 2,
        strBonus: 1,
        rangedStr: 1,
        def: { stab: 0, slash: 0, crush: 0, ranged: 0, magic: 0 },
        value: 50,
      },
      {
        kind: "equipment",
        id: "emerald-amulet",
        name: "Emerald Amulet",
        icon: "emerald-amulet",
        slot: "amulet",
        atkBonus: 6,
        strBonus: 4,
        rangedStr: 4,
        magicDamage: 3,
        def: { stab: 0, slash: 0, crush: 0, ranged: 0, magic: 2 },
        value: 120,
      },
      {
        kind: "equipment",
        id: "emerald-ring",
        name: "Emerald Ring",
        icon: "emerald-ring",
        slot: "ring",
        atkBonus: 4,
        strBonus: 2,
        rangedStr: 2,
        magicDamage: 2,
        def: { stab: 0, slash: 0, crush: 0, ranged: 0, magic: 1 },
        value: 100,
      },
      {
        kind: "equipment",
        id: "ruby-amulet",
        name: "Ruby Amulet",
        icon: "ruby-amulet",
        slot: "amulet",
        atkBonus: 10,
        strBonus: 7,
        rangedStr: 7,
        magicDamage: 5,
        def: { stab: 0, slash: 0, crush: 0, ranged: 0, magic: 3 },
        value: 220,
      },
      {
        kind: "equipment",
        id: "ruby-ring",
        name: "Ruby Ring",
        icon: "ruby-ring",
        slot: "ring",
        atkBonus: 6,
        strBonus: 4,
        rangedStr: 4,
        magicDamage: 3,
        def: { stab: 0, slash: 0, crush: 0, ranged: 0, magic: 2 },
        value: 180,
      },
      // Herblore wave (#118): herb Materials, dropped by the tiered Areas' own Monsters (see the
      // "#118: herb drop" comments on chicken/cow/goblin, wolf/goblin-warrior/bandit,
      // giant-rat/zombie/skeleton, and skeleton/crypt-shade's dropTables above) and consumed by the
      // Herblore recipes below. Append-only — after ruby-ring, never earlier.
      { kind: "material", id: "guam-herb", name: "Guam Herb", icon: "guam-herb", value: 4 },
      {
        kind: "material",
        id: "marrentill-herb",
        name: "Marrentill Herb",
        icon: "marrentill-herb",
        value: 6,
      },
      {
        kind: "material",
        id: "tarromin-herb",
        name: "Tarromin Herb",
        icon: "tarromin-herb",
        value: 8,
      },
      {
        kind: "material",
        id: "harralander-herb",
        name: "Harralander Herb",
        icon: "harralander-herb",
        value: 10,
      },
      // Herblore wave (#118): the charge potions brewed from the herbs above (see the Herblore
      // recipes below). `strength-potion`'s boostPct 0.20 / charges 50 is the owner's own worked
      // example ("+20% str for 50 attacks"); `fishing-potion`'s boostPct 0.15 / charges 40 is also
      // the owner's own worked example. `attack-potion`/`production-potion` mirror those shapes for
      // the combat-stat and skilling-speed target kinds the owner decision called for ("potions may
      // target combat stats ... and skilling speed").
      {
        kind: "potion",
        id: "strength-potion",
        name: "Strength Potion",
        icon: "strength-potion",
        target: "strength",
        boostPct: 0.2,
        charges: 50,
        value: 30,
      },
      {
        kind: "potion",
        id: "attack-potion",
        name: "Attack Potion",
        icon: "attack-potion",
        target: "attack",
        boostPct: 0.15,
        charges: 50,
        value: 30,
      },
      {
        kind: "potion",
        id: "fishing-potion",
        name: "Fishing Potion",
        icon: "fishing-potion",
        target: "fishing-speed",
        boostPct: 0.15,
        charges: 40,
        value: 25,
      },
      {
        kind: "potion",
        id: "production-potion",
        name: "Production Potion",
        icon: "production-potion",
        target: "production-speed",
        boostPct: 0.15,
        charges: 40,
        value: 25,
      },
      // Ammo wave (#119): arrow tiers (ranged's own resource, feeding the Quiver) and the four
      // Element runes (magic's resource, feeding the Rune Pouch) — both sold by the vendor below,
      // never dropped by Monsters this wave. Append-only — after production-potion, never earlier.
      // rangedStr climbs with tier, roughly the same spacing the dagger/bow atk/str ladders use
      // (bronze->steel->mithril, skipping iron — three tiers matches the issue's own "bronze/steel/
      // mithril or similar" suggestion).
      //
      // Economy check (owner-mandated arithmetic — see the issue's own worked numbers, §6): at
      // ~2,000 attacks/hr (idle, ~3 ticks/attack) and 1 arrow/attack, bronze-arrow's 3g vendor price
      // (below) costs ~6,000g/hr in ammo. Mid-game gold income runs ~15,000-20,000g/hr (e.g.
      // giant-rat's 30g guaranteed drop x ~600 kills/hr = ~18,000g/hr, the issue's own reference
      // rate) — 6,000/18,000 = ~33%, landing inside the issue's target ~30-40% gold-sink band:
      // meaningful, not bankrupting. Magic mirrors this at 1 rune/cast: a rune's 3g price (below,
      // picked to match bronze-arrow's own ratio rather than the issue's illustrative 4g) x ~2,000
      // casts/hr is also ~6,000g/hr, the same ~33% ratio — so switching between a bow and a staff
      // (see the Rune Pouch's own "no reload" test) never trades into a cheaper or pricier resource
      // sink, only a different one. steel-/mithril-arrow scale the SAME ratio at their own tier's
      // higher assumed gold income, so the sink stays proportionally ~30-40% up the whole ladder
      // rather than compounding into a bigger bite at higher tiers.
      {
        kind: "ammo",
        id: "bronze-arrow",
        name: "Bronze Arrow",
        icon: "bronze-arrow",
        ammoType: "arrow",
        rangedStr: 3,
        value: 1,
      },
      {
        kind: "ammo",
        id: "steel-arrow",
        name: "Steel Arrow",
        icon: "steel-arrow",
        ammoType: "arrow",
        rangedStr: 6,
        value: 2,
      },
      {
        kind: "ammo",
        id: "mithril-arrow",
        name: "Mithril Arrow",
        icon: "mithril-arrow",
        ammoType: "arrow",
        rangedStr: 10,
        value: 4,
      },
      {
        kind: "ammo",
        id: "air-rune",
        name: "Air Rune",
        icon: "air-rune",
        ammoType: "rune",
        element: "air",
        value: 1,
      },
      {
        kind: "ammo",
        id: "water-rune",
        name: "Water Rune",
        icon: "water-rune",
        ammoType: "rune",
        element: "water",
        value: 1,
      },
      {
        kind: "ammo",
        id: "earth-rune",
        name: "Earth Rune",
        icon: "earth-rune",
        ammoType: "rune",
        element: "earth",
        value: 1,
      },
      {
        kind: "ammo",
        id: "fire-rune",
        name: "Fire Rune",
        icon: "fire-rune",
        ammoType: "rune",
        element: "fire",
        value: 1,
      },
      // Gear Tier ladder (#251): the four new items this slice, appended at the end (append-only —
      // after fire-rune, never earlier, never inserted next to their tier-mates above).
      // bronze-chainbody/bronze-full-helm fill the bronze armour baseline that never existed before
      // (bronze shipped only bronze-shield + leather); steel-bar/mithril-bar are new Materials since
      // steel and mithril Equipment are now smithable (see the recipes array).
      ladderArmour("bronze", "chainbody"),
      ladderArmour("bronze", "full-helm"),
      { kind: "material", id: "steel-bar", name: "Steel Bar", icon: "steel-bar", value: 45 },
      { kind: "material", id: "mithril-bar", name: "Mithril Bar", icon: "mithril-bar", value: 90 },
      // Gear Tier ladder, tiers 5/6 (#252): adamant + rune appended on top of #251's builder — see
      // tier-ladder.ts's per-tier step table (the step steepens above mithril so rune gear still
      // out-classes the previous era, keeping rune-sword just under shade-blade). INTERIM BY
      // DESIGN: nothing yet drops adamant-bar/rune-bar and no chest contains this gear — see the
      // "currently unreachable" test in tier-ladder-reachability.test.ts; #254 wires up the drops
      // once the 5th Area lands. Family order per tier follows the issue's own "Full generated
      // Equipment" table (dagger, mace, sword, shortbow, staff, chainbody, kiteshield, full-helm).
      ladderWeapon("adamant", "dagger"),
      ladderWeapon("adamant", "mace"),
      ladderWeapon("adamant", "sword"),
      ladderWeapon("adamant", "shortbow"),
      ladderWeapon("adamant", "staff"),
      ladderArmour("adamant", "chainbody"),
      ladderArmour("adamant", "kiteshield"),
      ladderArmour("adamant", "full-helm"),
      ladderWeapon("rune", "dagger"),
      ladderWeapon("rune", "mace"),
      ladderWeapon("rune", "sword"),
      ladderWeapon("rune", "shortbow"),
      ladderWeapon("rune", "staff"),
      ladderArmour("rune", "chainbody"),
      ladderArmour("rune", "kiteshield"),
      ladderArmour("rune", "full-helm"),
      { kind: "material", id: "adamant-bar", name: "Adamant Bar", icon: "adamant-bar", value: 180 },
      { kind: "material", id: "rune-bar", name: "Rune Bar", icon: "rune-bar", value: 360 },
      // Ranged ammo parity with the new bows (#252) — mirrors the bronze/steel/mithril arrow shape
      // above; both are sold by the vendor below, never dropped (same interim-unreachable note).
      {
        kind: "ammo",
        id: "adamant-arrow",
        name: "Adamant Arrow",
        icon: "adamant-arrow",
        ammoType: "arrow",
        rangedStr: 14,
        value: 8,
      },
      {
        kind: "ammo",
        id: "rune-arrow",
        name: "Rune Arrow",
        icon: "rune-arrow",
        ammoType: "arrow",
        rangedStr: 18,
        value: 16,
      },
      // Gear Tier ladder (#342): platelegs appended after rune-arrow (append-only — existing item
      // ids above keep their exact array index). Six tiers bronze→rune; smithing recipes follow
      // at the end of the recipes array.
      ladderArmour("bronze", "platelegs"),
      ladderArmour("iron", "platelegs"),
      ladderArmour("steel", "platelegs"),
      ladderArmour("mithril", "platelegs"),
      ladderArmour("adamant", "platelegs"),
      ladderArmour("rune", "platelegs"),
    ],
    recipes: [
      // Gear Tier ladder (#251): generated by tier-ladder.ts's ladderRecipe, called in place — every
      // id below keeps its exact pre-#251 array index. Bronze reproduces exactly (see
      // tier-ladder.test.ts); iron's levelReq/xp move as part of the deliberate rebalance.
      ladderRecipe("bronze", "dagger"),
      ladderRecipe("bronze", "kiteshield"),
      ladderRecipe("bronze", "sword"),
      // Gap-fill crush weapon (#102): mirrors bronze-sword's recipe pattern, level-gated between
      // bronze-dagger and bronze-sword.
      ladderRecipe("bronze", "mace"),
      ladderRecipe("iron", "dagger"),
      ladderRecipe("iron", "chainbody"),
      // Gap-fill slash/crush weapons (#102): mirror bronze-sword/bronze-mace's recipe pattern,
      // level-gated between iron-dagger and iron-chainbody.
      ladderRecipe("iron", "mace"),
      ladderRecipe("iron", "sword"),
      // Cooking wave (#115): the #113 Recipe chassis's first non-Smithing content — converts a raw
      // catch (fishing spot / beast drop, see the items/dropTable comments above) into the matching
      // cooked Food. Owner decision, grilled and verbatim: "Raw drops + keep boss cooked" — a
      // level-1 recipe is mandatory so a fresh player is never foodless (cook-beef/cook-shrimp both
      // sit at levelReq 1, sourced respectively from Lumbry Meadows' beasts and its Shrimp Pool).
      //
      // Economy check (owner-mandated arithmetic, not vibes — see the issue's own worked numbers):
      // Shrimp Pool (catchChance 0.6, catchTicks 5) idles at 0.6/5 = ~144 raw-shrimp/hr (6000
      // ticks/hr). cook-shrimp's craftTicks 3 gives ~2000 cooks/hr of *capacity* with a full raw
      // stack, so fishing — not cooking speed — is always the bottleneck; the Fishing Spot domain
      // rule ("progression comes from unlocking better spots, not from scaling odds") holds. At xp
      // 30/cook, ~144/hr * 30 = ~4,300 Cooking xp/hr, enough to hit level 20 (4,470 xp) in about an
      // hour — a plausible early curve. Trout Run (0.5/5 = ~120 raw-trout/hr) at xp 70/cook gives
      // ~8,400 xp/hr for the mid-game jump to levelReq 15. cook-pike (levelReq 25) scales the same
      // way off Old Sewers' better catch rate, not off a faster Cooking action.
      {
        id: "cook-beef",
        name: "Cook Beef",
        skill: "cooking",
        levelReq: 1,
        inputs: [{ itemId: "raw-beef", qty: 1 }],
        outputItemId: "cooked-meat",
        xp: 30,
        craftTicks: 3,
      },
      {
        id: "cook-shrimp",
        name: "Cook Shrimp",
        skill: "cooking",
        levelReq: 1,
        inputs: [{ itemId: "raw-shrimp", qty: 1 }],
        outputItemId: "cooked-shrimp",
        xp: 30,
        craftTicks: 3,
      },
      {
        id: "cook-trout",
        name: "Cook Trout",
        skill: "cooking",
        levelReq: 15,
        inputs: [{ itemId: "raw-trout", qty: 1 }],
        outputItemId: "cooked-trout",
        xp: 70,
        craftTicks: 4,
      },
      {
        id: "cook-pike",
        name: "Cook Pike",
        skill: "cooking",
        levelReq: 25,
        inputs: [{ itemId: "raw-pike", qty: 1 }],
        outputItemId: "cooked-pike",
        xp: 90,
        craftTicks: 4,
      },
      // Crafting wave (#116): the #113 Recipe chassis's ranged-armour line — beasts drop hides (see
      // the "#116: hide drop" comments on chicken/cow/wolf/giant-rat's dropTables above), Crafting
      // converts them straight to leather/ranged armour (no cured intermediate — one-step, matching
      // Smithing's bar->gear chain). Owner framing (#76, verbatim): "ranged and jewelry/trinkets for
      // crafting" — this is the ranged-armour half; jewelry (#117) shares this Skill and tab.
      //
      // Economy check (owner-mandated arithmetic, not vibes — mirrors the issue's own worked
      // numbers): a mid-game farmer idles at ~600 kills/hr. Cow's Cowhide chance is 0.5/kill ->
      // ~300 hides/hr; craft-leather-body needs 1 Cowhide -> 300 crafts/hr of *capacity*, so the
      // Cowhide drop (not craft speed) is always the bottleneck, same as Cooking's own Fishing-spot-
      // bottlenecked design. At xp 25/craft -> ~7,500 Crafting xp/hr, hitting L30 (13,363 xp) in
      // ~1.8 hr — a plausible early curve (byte-identical to the issue's own worked example).
      // craft-leather-chaps/coif ride the same Cowhide bottleneck at slightly lower xp (22/20), so
      // their rate is proportionally close.
      //
      // The hard-leather tier (levelReq 20+) rides Wolf Hide (chance 0.4/kill -> ~240/hr from Wolf)
      // and Thick Hide (chance 0.35/kill -> ~210/hr from Giant Rat). craft-hard-leather-coif (1
      // input, xp 40) -> ~9,600 xp/hr, clearing L20->L25 (4470->7842, ~3,372 xp) in ~0.35 hr.
      // craft-hard-leather-chaps (2 inputs, halving the craft rate to ~120/hr, xp 55) -> ~6,600
      // xp/hr, clearing L25->L30 (~5,521 xp) in ~0.84 hr. craft-hard-leather-body (2 Thick Hide, xp
      // 70) -> ~105 crafts/hr * 70 = ~7,350 xp/hr, clearing L30->L40 (13,363->37,224, ~23,861 xp) in
      // ~3.25 hr. Every segment, base and hard-leather tier alike, lands well inside single-digit
      // hours from the same realistic 600-kills/hr assumption.
      {
        id: "craft-leather-body",
        name: "Leather Body",
        skill: "crafting",
        levelReq: 1,
        inputs: [{ itemId: "cowhide", qty: 1 }],
        outputItemId: "leather-body",
        xp: 25,
        craftTicks: 5,
      },
      {
        id: "craft-leather-chaps",
        name: "Leather Chaps",
        skill: "crafting",
        levelReq: 5,
        inputs: [{ itemId: "cowhide", qty: 1 }],
        outputItemId: "leather-chaps",
        xp: 22,
        craftTicks: 5,
      },
      {
        id: "craft-leather-coif",
        name: "Leather Coif",
        skill: "crafting",
        levelReq: 8,
        inputs: [{ itemId: "cowhide", qty: 1 }],
        outputItemId: "leather-coif",
        xp: 20,
        craftTicks: 4,
      },
      {
        id: "craft-hard-leather-coif",
        name: "Hard Leather Coif",
        skill: "crafting",
        levelReq: 20,
        inputs: [{ itemId: "wolf-hide", qty: 1 }],
        outputItemId: "hard-leather-coif",
        xp: 40,
        craftTicks: 6,
      },
      {
        id: "craft-hard-leather-chaps",
        name: "Hard Leather Chaps",
        skill: "crafting",
        levelReq: 25,
        inputs: [{ itemId: "wolf-hide", qty: 2 }],
        outputItemId: "hard-leather-chaps",
        xp: 55,
        craftTicks: 7,
      },
      {
        id: "craft-hard-leather-body",
        name: "Hard Leather Body",
        skill: "crafting",
        levelReq: 30,
        inputs: [{ itemId: "thick-hide", qty: 2 }],
        outputItemId: "hard-leather-body",
        xp: 70,
        craftTicks: 8,
      },
      // Crafting wave (#117): the #113 chassis's jewelry line — gems (see the "#117: gem drop"
      // comments on Darkroot/Old-Sewers/Bone-Crypt Monsters' dropTables above) cut straight to
      // amulet/ring jewelry (Crafting's own #76 framing, verbatim: "ranged and jewelry/trinkets for
      // crafting" — this is the jewelry half; #116 shipped the ranged-armour half). levelReqs
      // interleave INTO the existing leather ladder (12/16 sit between craft-leather-coif's 8 and
      // craft-hard-leather-coif's 20) rather than appending after it, then extend the ladder upward
      // for the emerald/ruby tiers (35-50), past the leather ladder's own top (30).
      //
      // Gem-drop-rate economy (owner-mandated, "a rare sink, not a grind ladder" — verbatim from the
      // issue): jewelry is NOT meant to be farmable the way leather is; it's an occasional bonus a
      // farmer stumbles into while grinding the Area for its usual kill-XP/gold, not something worth
      // camping for. Chances are picked in the issue's own ~1/64-1/256 rare-band range, scaled down
      // through the tiers as Areas get slower to clear (assumed farmer kill rates below are rough,
      // same "worked example" spirit as the leather-ladder comment above, not measured):
      // - Darkroot Forest (wolf/goblin-warrior/bandit, chance 1/96 each): ~300 kills/hr assumed ->
      //   combined ~9.4 Sapphire/hr, enough for 1-2 craft-sapphire-ring/-amulet per short session.
      // - Old Sewers (giant-rat/zombie/skeleton, chance 1/140 each): ~200 kills/hr assumed ->
      //   combined ~4.3 Emerald/hr, a handful per multi-hour session.
      // - Bone Crypt (crypt-shade only, chance 1/220): ~100 kills/hr assumed (single boss-tier
      //   Monster) -> ~0.45 Ruby/hr — the endgame gem stays a rare highlight-reel drop, not a
      //   craftable-every-session item.
      // Recipe xp (40-130, scaling with tier) is a bonus on top of the leather ladder's own xp/hr,
      // never the primary Crafting-leveling path — consistent with the gem supply being the
      // bottleneck (same "drop rate gates the pace, not craft speed" shape as #116's leather line).
      {
        id: "craft-sapphire-ring",
        name: "Sapphire Ring",
        skill: "crafting",
        levelReq: 12,
        inputs: [{ itemId: "sapphire", qty: 1 }],
        outputItemId: "sapphire-ring",
        xp: 40,
        craftTicks: 5,
      },
      {
        id: "craft-sapphire-amulet",
        name: "Sapphire Amulet",
        skill: "crafting",
        levelReq: 16,
        inputs: [{ itemId: "sapphire", qty: 1 }],
        outputItemId: "sapphire-amulet",
        xp: 50,
        craftTicks: 6,
      },
      {
        id: "craft-emerald-ring",
        name: "Emerald Ring",
        skill: "crafting",
        levelReq: 35,
        inputs: [{ itemId: "emerald", qty: 1 }],
        outputItemId: "emerald-ring",
        xp: 70,
        craftTicks: 6,
      },
      {
        id: "craft-emerald-amulet",
        name: "Emerald Amulet",
        skill: "crafting",
        levelReq: 40,
        inputs: [{ itemId: "emerald", qty: 1 }],
        outputItemId: "emerald-amulet",
        xp: 85,
        craftTicks: 7,
      },
      {
        id: "craft-ruby-ring",
        name: "Ruby Ring",
        skill: "crafting",
        levelReq: 45,
        inputs: [{ itemId: "ruby", qty: 1 }],
        outputItemId: "ruby-ring",
        xp: 110,
        craftTicks: 7,
      },
      {
        id: "craft-ruby-amulet",
        name: "Ruby Amulet",
        skill: "crafting",
        levelReq: 50,
        inputs: [{ itemId: "ruby", qty: 1 }],
        outputItemId: "ruby-amulet",
        xp: 130,
        craftTicks: 8,
      },
      // Herblore wave (#118): the #113 chassis's fourth non-Smithing content — brews herbs (see the
      // "#118: herb drop" comments on the tiered Areas' Monsters' dropTables above) straight into
      // charge potions (#118's PotionDef, consumed via the Potion Slot — see engine.ts's
      // assignLoadoutSlot/decrementPotionCharge). levelReqs climb with the herb tier, mirroring the
      // Cooking/Crafting ladders' own tier-interleaving shape.
      //
      // Economy check (owner-mandated arithmetic, verbatim from the issue's own worked example):
      // Guam Herb's drop chance is 0.15/kill; at a ~600-kills/hr farmer (this repo's own assumed
      // rate, same as the Crafting-wave comments above) that's ~90 herbs/hr -> ~90
      // brew-strength-potion crafts/hr of *capacity* (Herblore's own craft speed, craftTicks 5,
      // comfortably outpaces the drop-rate bottleneck, same "drop rate gates the pace" shape as
      // Cooking/Crafting). At xp 50/brew -> ~90 * 50 = ~4,500 Herblore xp/hr, clearing L1->L20
      // (~4,470 xp) in about an hour — the issue's own stated curve. A 50-charge Strength Potion
      // (owner's "+20% str for 50 attacks") covers ~50 player attacks (~1.5 min of unarmed-speed
      // combat, less with a faster weapon); sustaining the buff PERMANENTLY costs ~1 potion per
      // ~50 attacks, and at ~600 kills/hr (several attacks per kill) that's well under 90 potions/hr
      // — worked out by the issue as ~40 potions/hr, i.e. ~40 herbs/hr — comfortably under the ~90
      // herbs/hr drop rate. A buff is affordable but not free, matching the issue's own framing.
      // marrentill/tarromin/harralander-herb ride the same 0.15/kill chance from their own (slower-
      // clearing) Areas, so their brews scale down proportionally — a bonus on top of each Area's own
      // kill-XP/gold, not a dedicated grind target, same shape as the Crafting-wave gem ladder.
      {
        id: "brew-strength-potion",
        name: "Strength Potion",
        skill: "herblore",
        levelReq: 1, // was 3
        inputs: [{ itemId: "guam-herb", qty: 1 }],
        outputItemId: "strength-potion",
        xp: 50,
        craftTicks: 5,
      },
      {
        id: "brew-attack-potion",
        name: "Attack Potion",
        skill: "herblore",
        levelReq: 12,
        inputs: [{ itemId: "marrentill-herb", qty: 1 }],
        outputItemId: "attack-potion",
        xp: 65,
        craftTicks: 5,
      },
      {
        id: "brew-fishing-potion",
        name: "Fishing Potion",
        skill: "herblore",
        levelReq: 22,
        inputs: [{ itemId: "tarromin-herb", qty: 1 }],
        outputItemId: "fishing-potion",
        xp: 80,
        craftTicks: 6,
      },
      {
        id: "brew-production-potion",
        name: "Production Potion",
        skill: "herblore",
        levelReq: 32,
        inputs: [{ itemId: "harralander-herb", qty: 1 }],
        outputItemId: "production-potion",
        xp: 95,
        craftTicks: 6,
      },
      // Gear Tier ladder (#251): the 16 new Smithing Recipes this slice — every metal family now
      // has a Recipe at every tier (24 total: the 8 above plus these 16). Owner decision, verbatim:
      // "Smithable is always every item, but not every item can drop from monster." Appended at the
      // end (append-only — existing recipe ids above keep their exact array index).
      ladderRecipe("bronze", "chainbody"),
      ladderRecipe("bronze", "full-helm"),
      ladderRecipe("iron", "kiteshield"),
      ladderRecipe("iron", "full-helm"),
      ladderRecipe("steel", "dagger"),
      ladderRecipe("steel", "kiteshield"),
      ladderRecipe("steel", "sword"),
      ladderRecipe("steel", "mace"),
      ladderRecipe("steel", "chainbody"),
      ladderRecipe("steel", "full-helm"),
      ladderRecipe("mithril", "dagger"),
      ladderRecipe("mithril", "kiteshield"),
      ladderRecipe("mithril", "sword"),
      ladderRecipe("mithril", "mace"),
      ladderRecipe("mithril", "chainbody"),
      ladderRecipe("mithril", "full-helm"),
      // Gear Tier ladder, tiers 5/6 (#252): the 12 new Smithing Recipes this slice (6 metal
      // families x 2 tiers). Highest levelReq is rune-chainbody at 84 (75 + chainbody's +9 family
      // offset), comfortably under MAX_LEVEL 99 — see tier-ladder.test.ts. Appended at the end
      // (append-only — existing recipe ids above keep their exact array index).
      ladderRecipe("adamant", "dagger"),
      ladderRecipe("adamant", "mace"),
      ladderRecipe("adamant", "sword"),
      ladderRecipe("adamant", "chainbody"),
      ladderRecipe("adamant", "kiteshield"),
      ladderRecipe("adamant", "full-helm"),
      ladderRecipe("rune", "dagger"),
      ladderRecipe("rune", "mace"),
      ladderRecipe("rune", "sword"),
      ladderRecipe("rune", "chainbody"),
      ladderRecipe("rune", "kiteshield"),
      ladderRecipe("rune", "full-helm"),
      // Gear Tier ladder (#342): platelegs smithing recipes appended after rune-full-helm
      // (append-only). Highest levelReq remains rune-chainbody at 84; rune-platelegs is 81.
      ladderRecipe("bronze", "platelegs"),
      ladderRecipe("iron", "platelegs"),
      ladderRecipe("steel", "platelegs"),
      ladderRecipe("mithril", "platelegs"),
      ladderRecipe("adamant", "platelegs"),
      ladderRecipe("rune", "platelegs"),
    ],
    spells: [
      {
        id: "air-strike",
        name: "Air Strike",
        element: "air",
        levelReq: 1,
        baseMaxHit: 6,
        runeId: "air-rune",
      },
      {
        id: "water-strike",
        name: "Water Strike",
        element: "water",
        levelReq: 5,
        baseMaxHit: 9,
        runeId: "water-rune",
      },
      {
        id: "earth-strike",
        name: "Earth Strike",
        element: "earth",
        levelReq: 9,
        baseMaxHit: 12,
        runeId: "earth-rune",
      },
      {
        id: "fire-strike",
        name: "Fire Strike",
        element: "fire",
        levelReq: 13,
        baseMaxHit: 16,
        runeId: "fire-rune",
      },
    ],
    vendor: [
      { itemId: "bronze-arrow", price: 3 },
      { itemId: "steel-arrow", price: 6 },
      { itemId: "mithril-arrow", price: 10 },
      { itemId: "air-rune", price: 3 },
      { itemId: "water-rune", price: 3 },
      { itemId: "earth-rune", price: 3 },
      { itemId: "fire-rune", price: 3 },
      // Gear Tier ladder, tiers 5/6 (#252): the adamant/rune arrow tiers, priced at roughly the
      // same value-to-price ratio as mithril-arrow above (~2.5x value) — tuning, not spec.
      { itemId: "adamant-arrow", price: 20 },
      { itemId: "rune-arrow", price: 40 },
    ],
    pets: [
      {
        id: "rock-golem",
        name: "Rock Golem",
        icon: "rock-golem",
        target: "strength",
        boostPct: 0.01,
        source: "combat",
      },
      {
        id: "fishing-frog",
        name: "Fishing Frog",
        icon: "fishing-frog",
        target: "fishing-speed",
        boostPct: 0.01,
        source: "fishing",
      },
      {
        id: "kiln-cat",
        name: "Kiln Cat",
        icon: "kiln-cat",
        target: "production-speed",
        boostPct: 0.01,
        source: "production",
      },
      {
        id: "shade-wisp",
        name: "Shade Wisp",
        icon: "shade-wisp",
        target: "magic",
        boostPct: 0.02,
        source: { boss: "crypt-shade" },
      },
    ],
  },
);
